_commit: v1.12.1-1-g902fdaa
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: ''
name: shlink
namespace: shlink
pvc: false
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
upstreamURL: https://shlink.io/
url: https://github.com/charlesthomas/homelab-shlink
