---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: shlink
spec:
  target:
    name: mariadb
    deletionPolicy: Delete
  dataFrom:
    - sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      extract:
        key: shlink-mariadb
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink-api-key
  namespace: shlink
spec:
  target:
    name: shlink-api-key
    deletionPolicy: Delete
  data:
    - secretKey: api-token
      remoteRef:
        key: c747d59e-8f2f-4d66-a539-886792e3d1aa
        property: api-token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
