---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: shlink
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shlink
  namespace: shlink
  labels:
    app: shlink
    app.kubernetes.io/name: shlink
